openapi: 3.0.0
info:
  title: PhyisicsQA
  version: '1.0'
  description: Manage Phyisics Questions
  contact:
    name: Yaara Marcus
servers:
  - url: 'https://pwqmfe6648.execute-api.eu-central-1.amazonaws.com/dev'
tags:
  - name: PhyisicsQA
    description: PhyisicsQA API
paths:
  '/answers/{Id}':
    parameters:
      - schema:
          type: string
        name: Id
        in: path
        required: true
    post:
      tags: [PhyisicsQA]
      description: Create a new Answer
      operationId: post-questions-Id
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerPost'
  /answers/{Id}/rating:
    parameters:
      - name: "Id"
        in: "path"
        required: true
        schema:
           type: "string"
    post:
      tags: [PhyisicsQA]
      description: Update User Rating for answer
      operationId: post-rating-Id
      responses:
        "200":
          description: "200 response"
      requestBody:
        content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AnswerRating'
  /questions:
    get:
      tags: [PhyisicsQA]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionList'
        '400':
          description: Bad Request
      operationId: get-questions
      description: Get All Questions
    post:
      tags: [PhyisicsQA]
      operationId: post-questions
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      description: Post a new question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionPost'
  '/questions/{id}/answers':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - name: "user"
        in: "query"
        required: true
        schema:
           type: "string"
    get:
      tags: [PhyisicsQA]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnswerList'
      operationId: get-questions-id-answers
      description: Get Answers by question id
  '/questions/{id}/details':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags: [PhyisicsQA]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionPost'
      operationId: get-question-details
      description: Get Question Detaill By ID
components:
  schemas:
    AnswerList:
      title: AnswerList
      type: object
      properties:
        id:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
    AnswerPost:
      title: AnswerPost
      type: object
      description: Question Post Data
      properties:
        answerId:
          type: string
          maxLength: 20
          minLength: 20
        teacherName:
          type: string
          minLength: 5
          maxLength: 20
        date:
          type: string
          format: date-time
        message:
          type: string
          maxLength: 250
          minLength: 20
        questionId:
          type: string
      required:
        - answerId
        - teacherName
        - date
        - message
    Answer:
      title: Answer
      type: object
      description: Question Post Data
      properties:
        answerId:
          type: string
          maxLength: 20
          minLength: 20
        teacherName:
          type: string
          minLength: 5
          maxLength: 20
        date:
          type: string
          format: date-time
        message:
          type: string
          maxLength: 250
          minLength: 20
        questionId:
          type: string
        user_rating:
          type: number
        avg_rating:
          type: number
    QuestionList:
      title: QuestionList
      type: object
      properties:
        questions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionPost'
    QuestionPost:
      title: Question
      type: object
      description: Question Post Date
      properties:
        id:
          type: string
        userName:
          type: string
          minLength: 5
          maxLength: 20
        date:
          type: string
          format: date-time
        message:
          type: string
          maxLength: 250
          minLength: 20
    AnswerRating:
      title: AnswerRating
      type: object
      description: Answer Rating Post Data
      properties:
        user:
          type: string
          minLength: 5
          maxLength: 20
        rating:
          type: number
